#!/bin/sh

# Show info about available updates
if command -v apt >/dev/null 2>&1; then
    UPDATES=$(apt list --upgradeable 2>/dev/null | grep -vc Listing)
    if [ "$UPDATES" -gt 0 ]; then
        echo " * $UPDATES package(s) can be updated."
    else
        echo " * All packages are up to date."
    fi
fi
